DamascenoRafael/reminders-menubar

reminders-menu-bar/AppDelegate.swift
This makes things feel a lot faster.
Closes #8
=> Disable animation of the popover

reminders-menu-bar/Resources/de.lproj/Localizable.strings
=> Update for german translation

reminders-menu-bar/Resources/nl.lproj/Localizable.strings
Updated Dutch language, as stated/asked in #66
=> Updated Dutch language // #66

reminders-menu-bar/Resources/nl.lproj/Localizable.strings
https://github.com/DamascenoRafael/reminders-menubar/issues/66#issuecomment-1264226086
=> Update according to #66

reminders-menu-bar/Resources/zh-Hans.lproj/Localizable.strings
=> Update Simplified Chinese translation

reminders-menu-bar/Resources/es-419.lproj/Localizable.strings
Hi @DamascenoRafael I solve the issues related the last PR, I reopen now with the correct translations and removing the others commits. 😄
=> Updating localizables to Spanish

reminders-menu-bar/Resources/es-419.lproj/Localizable.strings
@DamascenoRafael  sorry, I didn't see this word in the Spanish translation 😨 
This is a Hotfix
=> Hotfixing Spanish localizables

reminders-menu-bar/Resources/de.lproj/Localizable.strings
see https://github.com/DamascenoRafael/reminders-menubar/issues/109
=> update german translation

reminders-menu-bar/Resources/nl.lproj/Localizable.strings
🇳🇱 Update Localizable.strings / #109
=> 🇳🇱 Update Localizable.strings / #109

reminders-menu-bar/Resources/ja.lproj/Localizable.strings
Hi! I updated the Japanese translation. I'm sorry to be late.
=> Update Japanese Translation

reminders-menubar/Resources/zh-Hans.lproj/Localizable.strings
"launchAtLoginOptionButton" = "登录时启动";
=> Update zh-Hans.lproj Localizable.strings

reminders-menubar/Resources/zh-Hans.lproj/Localizable.strings
=> Update Simplified Chinese localization

reminders-menubar/Resources/InfoPlist.xcstrings, reminders-menubar/Resources/Localizable.xcstrings
This pull request includes the following changes:
- Added missing Traditional Chinese translations to improve the completeness and readability of the documentation.
- Ensured that all documents and descriptions are available in Traditional Chinese to facilitate easier understanding for a broader audience of Traditional Chinese speakers.
We hope these changes will enhance the user experience and provide additional language support.
=> docs: add missing Traditional Chinese translations

reminders-menubar/Resources/Localizable.xcstrings
=> Update Italian locale

reminders-menubar/Resources/Localizable.xcstrings
=> Update KR locale

reminders-menubar/Resources/Localizable.xcstrings
Polish translations updated
Issue: #241
=> Update PL translations

reminders-menubar/Resources/Localizable.xcstrings
=> Update Dutch (NL), fixes #241

reminders-menubar/Resources/Localizable.xcstrings
Corrected the localisation of a string.
=> Correct it-IT locale

reminders-menubar/Resources/Localizable.xcstrings
Hi,
This pull request adds the missing Chinese (Traditional) translations and corrects existing inaccuracies within the documentation.
=> docs: Update  Chinese(Traditional) translations

reminders-menubar/Resources/Localizable.xcstrings
add missing `%i` placeholder in plural form
=> docs: Update Chinese(Traditional) translations

README.md, reminders-menubar.xcodeproj/project.pbxproj, reminders-menubar/Resources/InfoPlist.xcstrings, reminders-menubar/Resources/Localizable.xcstrings
What this PR does:
- Add Indonesian `id` translations to `Localizable.xcstrings` and `InfoPlist.xcstrings`
- Add Indonesian to the Readme
=> Add Indonesian `id` translations
